update laskurivi set sopimuslasku=null;
update sopimuslasku set laskurivi=null;
delete from laskurivi;
delete from sopimuslasku;
delete from lasku;
delete from sopimus;
delete from sopimustyyppi;
update henkilo set perhe=null;
delete from perhe;
update henkilo set osoite=null;
update henkilo set yhteystiedot=null;
delete from osoite;
delete from yhteystieto;
update harrastaja set huoltaja=null;
delete from vyokoe;
delete from vyoarvo;
delete from kisatulos;
delete from treenikaynti;
delete from treenisessiovetaja;
delete from treenisessio;
delete from treenivetaja;
delete from henkilorooli;
delete from rooli;
delete from harrastaja;
delete from henkilo;
delete from asetukset;