insert into vyoarvo (id, nimi, minimikuukaudet, minimitreenit, jarjestys) values (1, '8.kup', 2, 15, 1);
insert into vyoarvo (id, nimi, minimikuukaudet, minimitreenit, jarjestys) values (2, '7.kup', 3, 25, 2);
insert into vyoarvo (id, nimi, minimikuukaudet, minimitreenit, jarjestys) values (3, '6.kup', 3, 25, 3);
insert into vyoarvo (id, nimi, minimikuukaudet, minimitreenit, jarjestys) values (4, '5.kup', 3, 25, 4);
insert into vyoarvo (id, nimi, minimikuukaudet, minimitreenit, jarjestys) values (5, '4.kup', 4, 35, 5);
insert into vyoarvo (id, nimi, minimikuukaudet, minimitreenit, jarjestys) values (6, '3.kup', 4, 35, 6);
insert into vyoarvo (id, nimi, minimikuukaudet, minimitreenit, jarjestys) values (7, '2.kup', 5, 40, 7);
insert into vyoarvo (id, nimi, minimikuukaudet, minimitreenit, jarjestys) values (8, '1.kup', 6, 50, 8);
insert into vyoarvo (id, nimi, minimikuukaudet, minimitreenit, jarjestys) values (9, '1.dan', 6, 60, 9);
insert into vyoarvo (id, nimi, minimikuukaudet, minimitreenit, jarjestys) values (10, '2.dan', 24, 200, 10);
insert into vyoarvo (id, nimi, minimikuukaudet, minimitreenit, jarjestys) values (11, '3.dan', 36, 300, 11);
insert into sopimustyyppi(id, nimi, jasenmaksu, laskutettava, hinta) values (1, 'Jäsenmaksu', 'K', 'K', 10);
insert into sopimustyyppi(id, nimi, harjoittelumaksu, oletusmaksuvali, laskutettava, hinta, alaikaraja, ylaikaraja) values (2, 'Harjoittelu (4-6v)', 'K', 3, 'K', 19, 4, 6);
insert into sopimustyyppi(id, nimi, harjoittelumaksu, oletusmaksuvali, laskutettava, hinta, alaikaraja, ylaikaraja) values (3, 'Harjoittelu (7-17v)', 'K', 3, 'K', 29, 7, 17);
insert into sopimustyyppi(id, nimi, harjoittelumaksu, oletusmaksuvali, laskutettava, hinta, alaikaraja) values (4, 'Harjoittelu (18+v)', 'K', 3, 'K', 39, 18);
insert into sopimustyyppi(id, nimi, harjoittelumaksu, oletusmaksuvali, laskutettava, hinta, opiskelija) values (5, 'Harjoittelu (opisk.)', 'K', 3, 'K', 29, 'K');
insert into sopimustyyppi(id, nimi, treenikertoja, harjoittelumaksu, oletustreenikerrat, laskutettava, hinta) values (6, 'Kertamaksuja', 'K', 'K', 10, 'K', 6);
insert into sopimustyyppi(id, nimi, alkeiskurssi, harjoittelumaksu, jasenmaksu, oletuskuukaudetvoimassa, laskutettava, hinta, alaikaraja, ylaikaraja) values (7, 'Alkeiskurssi (7-15v/opisk)', 'K', 'K', 'K', 3, 'K', 149, 7, 15);
insert into sopimustyyppi(id, nimi, alkeiskurssi, harjoittelumaksu, jasenmaksu, oletuskuukaudetvoimassa, laskutettava, hinta, alaikaraja) values (8, 'Alkeiskurssi (16+)', 'K', 'K', 'K', 3, 'K', 179, 16);
insert into sopimustyyppi(id, nimi, jasenmaksu, harjoittelumaksu, koeaika, oletustreenikerrat, oletuskuukaudetvoimassa) values (9, 'Koeaika', 'K', 'K', 'K', 2, 1);
insert into sopimustyyppi(id, nimi, harjoittelumaksu, vapautus) values (10, 'Vapautus', 'K', 'K');
insert into sopimustyyppi(id, nimi, jasenmaksu, harjoittelumaksu, power) values (11, 'Power', 'K', 'K', 'K');
insert into sopimustyyppi(id, nimi, jasenmaksu, harjoittelumaksu, valmennuskeskus) values (12, 'Valmennuskeskus', 'K', 'K', 'K');
insert into asetukset(installaatio, saaja, iban, bic, viitenumero, osoite, postinumero, kaupunki, ytunnus, alvtunnus, puhelin, sahkoposti, kotisivut, viivastysprosentti, maksuaikaa, huomio, ylaotsikko) values ('Budokwai', 'Budokwai ry Taekwondo', 'OKOYFIHH', 'FI04 5711 6140 0501 84', 1, 'Kirstinkatu 1', '20200', 'Turku', '1012368-8', 'FI10123688', '0405960298', 'laskut@budokwai.fi', 'www.budokwai.fi/taekwondo', 5, 14, 'KÄYTTÄKÄÄ AINA\nVIITENUMEROA MAKSAESSANNE', 'LASKU');
insert into osoite(id, osoite, postinumero, kaupunki) values (1, 'Vaakunatie 10 as 7', '20780', 'Kaarina');
insert into yhteystieto(id, puhelinnumero, sahkoposti) values (1, '0405062266', 'nickarls@gmail.com');
insert into yhteystieto(id, puhelinnumero, sahkoposti) values (2, '0407218809', 'heidi.karlsson@abo.fi');
insert into perhe(id, nimi, osoite) values (1, 'Karlsson', 1);
insert into henkilo(id, etunimi, sukunimi, yhteystiedot, salasana, perhe) values (1, 'Nicklas', 'Karlsson', 1, '9DD4E461268C8034F5C8564E155C67A6', 1);
insert into henkilo(id, etunimi, sukunimi, yhteystiedot, salasana, perhe) values (2, 'Heidi', 'Karlsson', 2, '9DD4E461268C8034F5C8564E155C67A6', 1);
insert into henkilo(id, etunimi, sukunimi, salasana, perhe) values (3, 'Emil', 'Karlsson', '9DD4E461268C8034F5C8564E155C67A6', 1);
insert into harrastaja (id, jasennumero, lisenssinumero, syntynyt, sukupuoli) values (1, '28061975-1', '666', parsedatetime('28.06.1975', 'dd.MM.yyyy'), 'M');
insert into harrastaja (id, jasennumero, lisenssinumero, syntynyt, sukupuoli) values (2, '09081976-1', '667', parsedatetime('09.08.1976', 'dd.MM.yyyy'), 'N');
