insert into vyoarvo (id, nimi, kuvaus, minimikuukaudet, minimitreenit, jarjestys) values (1, '8.kup', 'Keltainen', 2, 15, 1);
insert into vyoarvo (id, nimi, kuvaus, minimikuukaudet, minimitreenit, jarjestys) values (2, '7.kup', 'Keltainen+natsa', 3, 25, 2);
insert into vyoarvo (id, nimi, kuvaus, minimikuukaudet, minimitreenit, jarjestys) values (3, '6.kup', 'Vihreä', 3, 25, 3);
insert into vyoarvo (id, nimi, kuvaus, minimikuukaudet, minimitreenit, jarjestys) values (4, '5.kup', 'Vihreä+natsa', 3, 25, 4);
insert into vyoarvo (id, nimi, kuvaus, minimikuukaudet, minimitreenit, jarjestys) values (5, '4.kup', 'Sininen', 4, 35, 5);
insert into vyoarvo (id, nimi, kuvaus, minimikuukaudet, minimitreenit, jarjestys) values (6, '3.kup', 'Sininen+natsa', 4, 35, 6);
insert into vyoarvo (id, nimi, kuvaus, minimikuukaudet, minimitreenit, jarjestys) values (7, '2.kup', 'Punainen', 5, 40, 7);
insert into vyoarvo (id, nimi, kuvaus, minimikuukaudet, minimitreenit, jarjestys) values (8, '1.kup', 'Punainen+natsa', 6, 50, 8);
insert into vyoarvo (id, nimi, kuvaus, minimikuukaudet, minimitreenit, jarjestys) values (9, '1.dan', 'Musta I', 6, 60, 9);
insert into vyoarvo (id, nimi, kuvaus, minimikuukaudet, minimitreenit, jarjestys) values (10, '2.dan', 'Musta II', 24, 200, 10);
insert into vyoarvo (id, nimi, kuvaus, minimikuukaudet, minimitreenit, jarjestys) values (11, '3.dan', 'Musta III', 36, 300, 11);
insert into sopimustyyppi(id, nimi, jasenmaksu, laskutettava, hinta) values (1, 'Jäsenmaksu', 'K', 'K', 10);
insert into sopimustyyppi(id, nimi, harjoittelumaksu, oletusmaksuvali, laskutettava, hinta, alaikaraja, ylaikaraja) values (2, 'Harjoittelu (4-6v)', 'K', 3, 'K', 19, 4, 6);
insert into sopimustyyppi(id, nimi, harjoittelumaksu, oletusmaksuvali, laskutettava, hinta, alaikaraja, ylaikaraja) values (3, 'Harjoittelu (7-17v)', 'K', 3, 'K', 29, 7, 17);
insert into sopimustyyppi(id, nimi, harjoittelumaksu, oletusmaksuvali, laskutettava, hinta, alaikaraja) values (4, 'Harjoittelu (18+v)', 'K', 3, 'K', 39, 18);
insert into sopimustyyppi(id, nimi, harjoittelumaksu, oletusmaksuvali, laskutettava, hinta, opiskelija) values (5, 'Harjoittelu (opisk.)', 'K', 3, 'K', 29, 'K');
insert into sopimustyyppi(id, nimi, treenikertoja, harjoittelumaksu, oletustreenikerrat, laskutettava, hinta) values (6, 'Kertamaksuja', 'K', 'K', 10, 'K', 6);
insert into sopimustyyppi(id, nimi, alkeiskurssi, harjoittelumaksu, jasenmaksu, oletuskuukaudetvoimassa, laskutettava, hinta, alaikaraja, ylaikaraja) values (7, 'Alkeiskurssi (7-15v/opisk)', 'K', 'K', 'K', 3, 'K', 149, 7, 15);
insert into sopimustyyppi(id, nimi, alkeiskurssi, harjoittelumaksu, jasenmaksu, oletuskuukaudetvoimassa, laskutettava, hinta, alaikaraja) values (8, 'Alkeiskurssi (16+)', 'K', 'K', 'K', 3, 'K', 179, 16);
insert into sopimustyyppi(id, nimi, jasenmaksu, harjoittelumaksu, koeaika, oletustreenikerrat, oletuskuukaudetvoimassa) values (9, 'Koeaika', 'K', 'K', 'K', 2, 1);
insert into sopimustyyppi(id, nimi, harjoittelumaksu, vapautus) values (10, 'Vapautus', 'K', 'K');
insert into sopimustyyppi(id, nimi, jasenmaksu, harjoittelumaksu, power) values (11, 'Power', 'K', 'K', 'K');
insert into sopimustyyppi(id, nimi, jasenmaksu, harjoittelumaksu, valmennuskeskus) values (12, 'Valmennuskeskus', 'K', 'K', 'K');
insert into asetukset(installaatio, saaja, iban, bic, viitenumero, osoite, postinumero, kaupunki, ytunnus, alvtunnus, puhelin, sahkoposti, kotisivut, viivastysprosentti, maksuaikaa, huomio, ylaotsikko) values ('Budokwai', 'Budokwai ry Taekwondo', 'OKOYFIHH', 'FI04 5711 6140 0501 84', 1, 'Kirstinkatu 1', '20200', 'Turku', '1012368-8', 'FI10123688', '0405960298', 'laskut@budokwai.fi', 'www.budokwai.fi/taekwondo', 5, 14, 'KÄYTTÄKÄÄ AINA\nVIITENUMEROA MAKSAESSANNE', 'LASKU');

