insert into vyoarvo (id, nimi, kuvaus, minimikuukaudet, minimitreenit, jarjestys) values (1, '8.kup', 'Keltainen', 2, 15, 1);
insert into vyoarvo (id, nimi, kuvaus, minimikuukaudet, minimitreenit, jarjestys) values (2, '7.kup', 'Keltainen+natsa', 3, 25, 2);
insert into vyoarvo (id, nimi, kuvaus, minimikuukaudet, minimitreenit, jarjestys) values (3, '6.kup', 'Vihreä', 3, 25, 3);
insert into vyoarvo (id, nimi, kuvaus, minimikuukaudet, minimitreenit, jarjestys) values (4, '5.kup', 'Vihreä+natsa', 3, 25, 4);
insert into vyoarvo (id, nimi, kuvaus, minimikuukaudet, minimitreenit, jarjestys) values (5, '4.kup', 'Sininen', 4, 35, 5);
insert into vyoarvo (id, nimi, kuvaus, minimikuukaudet, minimitreenit, jarjestys) values (6, '3.kup', 'Sininen+natsa', 4, 35, 6);
insert into vyoarvo (id, nimi, kuvaus, minimikuukaudet, minimitreenit, jarjestys) values (7, '2.kup', 'Punainen', 5, 40, 7);
insert into vyoarvo (id, nimi, kuvaus, minimikuukaudet, minimitreenit, jarjestys) values (8, '1.kup', 'Punainen+natsa', 6, 50, 8);
insert into vyoarvo (id, nimi, kuvaus, minimikuukaudet, minimitreenit, jarjestys, poom) values (9, '1.poom', 'Poom I', 6, 60, 9, 'K');
insert into vyoarvo (id, nimi, kuvaus, minimikuukaudet, minimitreenit, jarjestys, dan) values (10, '1.dan', 'Dan I', 6, 60, 10, 'K');
insert into vyoarvo (id, nimi, kuvaus, minimikuukaudet, minimitreenit, jarjestys, poom) values (11, '2.poom', 'Poom II', 24, 200, 11, 'K');
insert into vyoarvo (id, nimi, kuvaus, minimikuukaudet, minimitreenit, jarjestys, dan) values (12, '2.dan', 'Dan II', 24, 200, 12, 'K');
insert into vyoarvo (id, nimi, kuvaus, minimikuukaudet, minimitreenit, jarjestys, poom) values (13, '3.poom', 'Poom III', 36, 300, 13, 'K');
insert into vyoarvo (id, nimi, kuvaus, minimikuukaudet, minimitreenit, jarjestys, dan) values (14, '3.dan', 'Dan III', 36, 300, 14, 'K');
insert into vyoarvo (id, nimi, kuvaus, minimikuukaudet, minimitreenit, jarjestys, poom) values (15, '4.poom', 'Poom IV', 48, 400, 15, 'K');
insert into vyoarvo (id, nimi, kuvaus, minimikuukaudet, minimitreenit, jarjestys, dan) values (16, '4.dan', 'Dan IV', 48, 400, 16, 'K');
insert into vyoarvo (id, nimi, kuvaus, minimikuukaudet, minimitreenit, jarjestys, dan) values (17, '5.dan', 'Dan V', 60, 500, 17, 'K');
insert into vyoarvo (id, nimi, kuvaus, minimikuukaudet, minimitreenit, jarjestys, dan) values (18, '6.dan', 'Dan VI', 72, 600, 18, 'K');
insert into sopimustyyppi(id, nimi, jasenmaksu, laskutettava, hinta) values (1, 'Jäsenmaksu', 'K', 'K', 10);
insert into sopimustyyppi(id, nimi, harjoittelumaksu, oletusmaksuvali, laskutettava, hinta, alaikaraja, ylaikaraja) values (2, 'Harjoittelu (4-6v)', 'K', 3, 'K', 19, 4, 6);
insert into sopimustyyppi(id, nimi, harjoittelumaksu, oletusmaksuvali, laskutettava, hinta, alaikaraja, ylaikaraja) values (3, 'Harjoittelu (7-17v)', 'K', 3, 'K', 29, 7, 17);
insert into sopimustyyppi(id, nimi, harjoittelumaksu, oletusmaksuvali, laskutettava, hinta, alaikaraja) values (4, 'Harjoittelu (18+v)', 'K', 3, 'K', 39, 18);
insert into sopimustyyppi(id, nimi, harjoittelumaksu, oletusmaksuvali, laskutettava, hinta, opiskelija) values (5, 'Harjoittelu (opisk.)', 'K', 3, 'K', 29, 'K');
insert into sopimustyyppi(id, nimi, treenikertoja, harjoittelumaksu, oletustreenikerrat, laskutettava, hinta) values (6, 'Kertamaksuja', 'K', 'K', 10, 'K', 6);
insert into sopimustyyppi(id, nimi, alkeiskurssi, harjoittelumaksu, jasenmaksu, oletuskuukaudetvoimassa, laskutettava, hinta, alaikaraja, ylaikaraja) values (7, 'Alkeiskurssi (7-15v/opisk)', 'K', 'K', 'K', 3, 'K', 149, 7, 15);
insert into sopimustyyppi(id, nimi, alkeiskurssi, harjoittelumaksu, jasenmaksu, oletuskuukaudetvoimassa, laskutettava, hinta, alaikaraja) values (8, 'Alkeiskurssi (16+)', 'K', 'K', 'K', 3, 'K', 179, 16);
insert into sopimustyyppi(id, nimi, jasenmaksu, harjoittelumaksu, koeaika, oletustreenikerrat, oletuskuukaudetvoimassa) values (9, 'Koeaika', 'K', 'K', 'K', 2, 1);
insert into sopimustyyppi(id, nimi, harjoittelumaksu, vapautus) values (10, 'Vapautus', 'K', 'K');
insert into sopimustyyppi(id, nimi, jasenmaksu, harjoittelumaksu, power) values (11, 'Power', 'K', 'K', 'K');
insert into sopimustyyppi(id, nimi, jasenmaksu, harjoittelumaksu, valmennuskeskus) values (12, 'Valmennuskeskus', 'K', 'K', 'K');
insert into asetukset(installaatio, saaja, iban, bic, viitenumero, osoite, postinumero, kaupunki, ytunnus, alvtunnus, puhelin, sahkoposti, kotisivut, viivastysprosentti, maksuaikaa, huomio, ylaotsikko, ghostScript) values ('Budokwai', 'Budokwai ry Taekwondo', 'OKOYFIHH', 'FI04 5711 6140 0501 84', 1, 'Kirstinkatu 1', '20200', 'Turku', '1012368-8', 'FI10123688', '0405960298', 'laskut@budokwai.fi', 'www.budokwai.fi/taekwondo', 5, 14, 'KÄYTTÄKÄÄ AINA\nVIITENUMEROA MAKSAESSANNE', 'LASKU', 'C:/Progra~1/gs/gs9.16/bin/gswin64c.exe');

